version: '3.9'
services:
  db:
    image: postgres:15
    container_name: pg_db
    environment:
      POSTGRES_DB: anagram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: anagram_service
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: anagram_db
      DB_USER: postgres
      DB_PASSWORD: root

volumes:
  postgres-data:
