"""word table migration

Revision ID: b485f0245c12
Revises: 
Create Date: 2024-12-25 15:00:59.786238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b485f0245c12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_words_sorted_word', table_name='words')
    op.drop_table('words')
    op.drop_index('ix_request_log_endpoint', table_name='request_log')
    op.drop_index('ix_request_log_timestamp', table_name='request_log')
    op.drop_table('request_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processing_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('word', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='request_log_pkey')
    )
    op.create_index('ix_request_log_timestamp', 'request_log', ['timestamp'], unique=False)
    op.create_index('ix_request_log_endpoint', 'request_log', ['endpoint'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sorted_word', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='words_pkey'),
    sa.UniqueConstraint('word', name='words_word_key')
    )
    op.create_index('ix_words_sorted_word', 'words', ['sorted_word'], unique=False)
    # ### end Alembic commands ###
